# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2204"
  config.vm.network "private_network", ip: "10.10.11.33", netmask: "255.255.255.0"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu2204"
    vb.memory = "2048"
  end
end


