# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2204"

  config.vm.hostname = "UbuntuBash"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.name = "UbuntuBash"
  end

end
