# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2204"

  config.vm.hostname = "UbuntuBash2"
  config.vm.network "private_network", ip: "172.16.0.33", netmask:"255.255.0.0"
  config.vm.synced_folder "./CarpetaSync", "/script"



  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.name = "UbuntuBash2"
  end

end
